
PROCESSING_JAVA=processing-java
SKETCH_NAME=$(shell pwd)
COMPILE_OPTIONS= --run --force

all: sketch

sketch: 
	${PROCESSING_JAVA} --sketch=${SKETCH_NAME} --output=${SKETCH_NAME}/build ${COMPILE_OPTIONS}


